name: outline_editor
description: "an outline style rich text editor made with super_editor"
version: 0.0.4
publish_to: none
#homepage:


environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: 2367_add-more-specific-selection-change-types
      # ref: main
#  super_editor_markdown:
#    git:
#      url: https://github.com/superlistapp/super_editor
#      path: super_editor_markdown
#      ref: main
#  super_text_layout:
#    git:
#      url: https://github.com/superlistapp/super_editor.git
#      path: super_text_layout
#      ref: main
  attributed_text: ^0.4.4
  logging: ^1.3.0
  uuid: ^4.5.1
  collection: ^1.19.1


# dependency_overrides:
#   super_editor:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: super_editor
#       ref: main # or "main"
#   super_editor_markdown:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: super_editor_markdown
#       ref: main
#   super_text_layout:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: super_text_layout
#       ref: main
#   attributed_text:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: attributed_text
#       ref: main
#dependency_overrides:
# super_editor:
#   path: ../super_editor/super_editor
# super_editor_markdown:
#   path: ../super_editor/super_editor_markdown
# super_text_layout:
#   path: ../super_editor/super_text_layout
# attributed_text:
#   path: ../super_editor/attributed_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_test_runners: ^0.0.4
  flutter_lints: ^5.0.0
  flutter_test_robots: ^0.0.24

flutter:
