name: example_editor
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logging: ^1.3.0
  outline_editor:
    path: ..
  super_editor_markdown: ^0.1.7

# dependency_overrides:
#   super_editor:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: super_editor
#       ref: main # or "main"
#   super_editor_markdown:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: super_editor_markdown
#       ref: main
#   super_text_layout:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: super_text_layout
#       ref: main
#   attributed_text:
#     git:
#       url: https://github.com/superlistapp/super_editor
#       path: attributed_text
#       ref: main

dependency_overrides:
 super_editor:
   path: ../../super_editor/super_editor
 super_editor_markdown:
   path: ../../super_editor/super_editor_markdown
 super_text_layout:
   path: ../../super_editor/super_text_layout
 attributed_text:
   path: ../../super_editor/attributed_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
